export const errorMessage = {
  selectType: "error.selectType",
  unknown: "error.unknown",
  postTitle: "error.postTitle",
  login: "error.login",
  candidateLength: "error.candidateLength",
  noCandidateTitle: "error.noCandidateTitle",
  noCandidateImage: "error.noCandidateImage",
  candidateError: "error.candidateError",
  tournamentCandidateLength: "error.tournamentCandidateLength",
  overTenUserName: "error.overTenUserName",
  noUserName: "error.noUserName",
  noPassword: "error.noPassword",
  notSamePassword: "error.notSamePassword",
  noEmail: "error.noEmail",
  existEmail: "error.existEmail",
  invalidEmail: "error.invalidEmail",
  safePassword: "error.safePassword",
  loginFailBadRequest: "error.loginFailBadRequest",
  alreadySignupGoogle: "error.alreadySignupGoogle",
  alreadySignupFacebook: "error.alreadySignupFacebook",
  alreadySignupInstagram: "error.alreadySignupInstagram",
  alreadySignupTwitter: "error.alreadySignupTwitter",
  clear: "error.clear",
} as const

export const successMessage = {
  voted: "success.voted",
  login: "success.login",
  register: "success.register",
  loginNewPost: "success.loginNewPost",
  posting: "success.posting",
  commenting: "success.commenting",
  copyLink: "success.copyLink",
} as const
